insert into public."City" ("Name", "addres") values ('Pengilon', '01973 Carpenter Circle');
insert into public."City" ("Name", "addres") values ('Huancapallac', '63 Columbus Trail');
insert into public."City" ("Name", "addres") values ('Arroio Grande', '537 Fremont Terrace');
insert into public."City" ("Name", "addres") values ('Brudzeń Duży', '498 Manufacturers Road');
insert into public."City" ("Name", "addres") values ('Thị Trấn Cẩm Thủy', '0 Shelley Parkway');
insert into public."City" ("Name", "addres") values ('Porkhov', '290 Packers Crossing');
insert into public."City" ("Name", "addres") values ('Alistráti', '8 Maple Wood Circle');
insert into public."City" ("Name", "addres") values ('Wairiang', '79393 Thackeray Trail');
insert into public."City" ("Name", "addres") values ('Hōjō', '85835 Center Crossing');
insert into public."City" ("Name", "addres") values ('São Domingos do Maranhão', '3058 Magdeline Avenue');
insert into public."City" ("Name", "addres") values ('Sake', '55 Morningstar Junction');
insert into public."City" ("Name", "addres") values ('Tsurib', '0 Hudson Plaza');
insert into public."City" ("Name", "addres") values ('Tlogotunggal', '41119 Bluejay Drive');
insert into public."City" ("Name", "addres") values ('Cunliji', '887 Heath Circle');
insert into public."City" ("Name", "addres") values ('Inari', '4 Eagan Street');
insert into public."City" ("Name", "addres") values ('Tysmenychany', '648 Vernon Parkway');
insert into public."City" ("Name", "addres") values ('Puerto Nariño', '5 Roxbury Trail');
insert into public."City" ("Name", "addres") values ('Kabare', '1 Knutson Lane');
insert into public."City" ("Name", "addres") values ('Jieshui', '473 Sycamore Court');
insert into public."City" ("Name", "addres") values ('Valencia', '9917 Vera Pass');
insert into public."City" ("Name", "addres") values ('Atlanta', '64222 Hoffman Center');
insert into public."City" ("Name", "addres") values ('Blois', '77363 Sauthoff Way');
insert into public."City" ("Name", "addres") values ('Brunflo', '08383 La Follette Junction');
insert into public."City" ("Name", "addres") values ('Retenggoma', '429 Hanson Circle');
insert into public."City" ("Name", "addres") values ('Buawan', '05 Sullivan Circle');
insert into public."City" ("Name", "addres") values ('Kiaranonggeng', '20 Hanson Way');
insert into public."City" ("Name", "addres") values ('Buchou', '902 Meadow Vale Crossing');
insert into public."City" ("Name", "addres") values ('Qal‘at al Andalus', '981 Caliangt Center');
insert into public."City" ("Name", "addres") values ('Valdemarsvik', '48833 Oak Valley Hill');
insert into public."City" ("Name", "addres") values ('Lendangara Satu', '2 Eastwood Terrace');
