insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2018-04-06', 6, 5, 17);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Suspendisse potenti.', '2012-11-26', 7, 1, 21);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Vestibulum rutrum rutrum neque.', '2013-08-04', 8, 5, 1);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Duis ac nibh.', '2019-07-06', 8, 4, 11);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Vivamus in felis eu sapien cursus vestibulum.', '2014-07-31', 10, 1, 3);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2018-04-25', 9, 4, 14);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Etiam justo.', '2020-03-03', 6, 1, 6);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Morbi non lectus.', '2022-12-21', 7, 5, 8);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Proin at turpis a pede posuere nonummy.', '2016-01-02', 9, 2, 1);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Suspendisse potenti.', '2015-03-22', 8, 4, 13);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2016-02-24', 9, 4, 10);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Praesent lectus.', '2019-11-06', 8, 6, 28);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Fusce posuere felis sed lacus.', '2019-03-07', 7, 5, 17);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Aliquam quis turpis eget elit sodales scelerisque.', '2018-03-12', 4, 4, 21);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Nulla facilisi.', '2021-03-14', 8, 2, 8);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Suspendisse accumsan tortor quis turpis.', '2019-04-18', 10, 2, 28);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Nam tristique tortor eu pede.', '2020-04-16', 8, 5, 18);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Integer ac neque.', '2020-06-24', 8, 3, 29);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Duis aliquam convallis nunc.', '2019-10-06', 4, 1, 26);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Donec ut dolor.', '2016-05-25', 4, 4, 19);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Quisque ut erat.', '2012-03-16', 9, 4, 23);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Cras in purus eu magna vulputate luctus.', '2010-09-17', 8, 3, 21);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Fusce consequat.', '2021-05-11', 10, 5, 7);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2021-09-20', 5, 4, 26);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2017-12-21', 8, 5, 13);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Duis consequat dui nec nisi volutpat eleifend.', '2011-08-24', 5, 6, 3);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Sed sagittis.', '2020-12-30', 6, 6, 7);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Fusce posuere felis sed lacus.', '2020-06-11', 5, 5, 29);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2014-11-21', 6, 3, 9);
insert into public."Report" ("Report", "Datetime", "idDeforest", "idAffectation", "idCity") values ('Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2015-01-22', 5, 6, 26);
