# Nombre del archivo: azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Cambia esto si tu rama principal tiene otro nombre

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      cd backend
      echo "DB_HOST=servicio-postgres.postgres.database.azure.com" >> .env
      echo "DB_PORT=5432" >> .env
      echo "DB_USERNAME=postgres" >> .env
      echo "DB_PASSWORD=kiup-QUY.+*1094Rxsdp;uy" >> .env
      echo "DB_NAME=proyect" >> .env
      npm install
      npm run start:prod
    displayName: 'Instalar dependencias del backend y ejecutar'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js para el frontend'

  - script: |
      cd frontend-haltoforest
      echo "export const environment = { production: false, url: 'http://localhost:3000', apimaps: 'AIzaSyBMImNUsVNZW3oJMdaOUg8QQPb0ZUcPi_g' };" > src/environments/environment.ts
      npm install
      ng serve --port 8000
    displayName: 'Instalar dependencias del frontend y ejecutar'
